name: Trigger auto deployment for studymentor-api

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/studymentor-api-AutoDeployTrigger-456f1c67-5679-461d-b8be-06250aa97be8.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.STUDYMENTORAPI_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/backend
          dockerfilePath: Dockerfile
          registryUrl: docker.io
          registryUsername: ${{ secrets.STUDYMENTORAPI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.STUDYMENTORAPI_REGISTRY_PASSWORD }}
          containerAppName: studymentor-api
          resourceGroup: studymentor-rg
          imageToBuild: fatmanurkaragoz/studymentor-api:${{ github.sha }}
          targetPort: 8080
          
            

     

